build:
  desc: create application binary
  cmds:
    - go build -o bin/app

clean:
  desc: removes application binaries
  cmds:
    - rm bin/*

dev:
  desc: run application binary in development
  cmds:
    - task build
    - APP_ENV=dev ./bin/app

